name: python_ffi_poc
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  python_ffi: ^0.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  dartpip: ^0.1.0

dependency_overrides:
  collection: ^1.18.0
  dartpip:
    git:
      url: https://github.com/IVLIVS-III/dart_python_ffi.git
      path: packages/dartpip
      ref: f6eb62d8e78fb883ae5f8fc1133c985306d28067
  dartpip_solver:
    git:
      url: https://github.com/IVLIVS-III/dart_python_ffi.git
      path: packages/dartpip_solver
      ref: f6eb62d8e78fb883ae5f8fc1133c985306d28067
  python_ffi:
    git:
      url: https://github.com/IVLIVS-III/dart_python_ffi.git
      path: packages/python_ffi
      ref: f6eb62d8e78fb883ae5f8fc1133c985306d28067
  python_ffi_cpython:
    git:
      url: https://github.com/IVLIVS-III/dart_python_ffi.git
      path: packages/python_ffi_cpython
      ref: f6eb62d8e78fb883ae5f8fc1133c985306d28067
  python_ffi_interface:
    git:
      url: https://github.com/IVLIVS-III/dart_python_ffi.git
      path: packages/python_ffi_interface
      ref: f6eb62d8e78fb883ae5f8fc1133c985306d28067
  python_ffi_lint:
    git:
      url: https://github.com/IVLIVS-III/dart_python_ffi.git
      path: packages/python_ffi_lint
      ref: f6eb62d8e78fb883ae5f8fc1133c985306d28067

flutter:
  assets:
    - python-modules/excel_test.py
    - python-modules/basic_operations.py
    - python-modules/python_ffi.py
    - python-modules/modules.json
  uses-material-design: true

python_ffi:
  modules:
    basic_operations: any
    excel_test: any
